### ISSUE TITLE
renameKey behaviour misleading and potentially invalid

### ISSUE THREAD

**Issue by tnajdek** [assemble/assemble#698] opened 2015-04-26 01:09 UTC
Currently renameKey boils down to:

    path.basename(myJs, path.extname(myJs));

Which might result in unexpected, hard to debug problem, consider the following example:

    var myCss = 'foo.bar.css'
    var myJs = 'foo.bar.js'
    path.basename(myJs, path.extname(myJs)); //'foo.bar'
    path.basename(myCss, path.extname(myCss)); //'foo.bar'

If `assemble.src` encounters files as above (i.e. `foo.bar.css` and `foo.bar.js`), collision occurs masking one of the files.

I would say `renameKey` should be an optional opt-in to avoid confusion.

Somewhat related to #619.

**Comment by jonschlinkert** [comment] 2015-04-26 01:16
> I would say renameKey should be an optional opt-in to avoid confusion.

what would the default be then?

**Comment by jonschlinkert** [comment] 2015-04-26 01:17
> Somewhat related to #619.

also, yes, `renameKey` is the solution to 619. not the cause.

**Comment by tnajdek** [comment] 2015-04-26 11:03
Hey @jonschlinkert, thanks for coming back to me so soon.

I was bit confused by `renameKey` and only now begin to understand how it's being used by template loader/renderer etc.. While it completely makes sense for assemble, it will have adverse effects for some gulp plugins used within assemble and when it does it's hard to understand what's going on without spending hours looking into assemble itself.

That being said I can't think of any better solution at the moment. For me a workaround was to switch to `gulp` for generic tasks and use `gulp-assemble` wrapper for assemble-specific stuff, perhaps a solution is to advertised this as a default approach for non-trivial projects.

btw: thanks for all the great work on assemble!

**Comment by jonschlinkert** [comment] 2015-04-26 17:27
glad you figured everything out. 

> perhaps a solution is to advertised this as a default approach for non-trivial projects.

our solution is to not use gulp at all on non-trivial projects

can this be closed? thanks!

**Comment by jonschlinkert** [comment] 2015-09-13 02:13
closing, since it seems to be resolved

**Closed by jonschlinkert** 2015-09-13 02:13 UTC
