### ISSUE TITLE
v0.6.0 Timings

### ISSUE THREAD

**Issue by agross** [assemble/assemble#650] opened 2015-02-27 13:35 UTC
I created some more timing statistics with our fairly large set of product pages to generate. We have source "group" JSON files with several products in each JSON. `10.json` has all the products in group 10. The groups differ in sizes, there are large and small groups.

While assemble is reasonably fast there still seem to be a non-linearity during runtime. E.g. for large data sets the runtime will increase non-linearly.

![2015-02-27_14-32-09](https://cloud.githubusercontent.com/assets/16245/6413221/7936f988-be8d-11e4-8cf3-ac02f18d0165.png)

Note that generating all groups after another in several gulp/assemble runs takes about 9 minutes. Generating all products on the other hand, takes about 29 minutes.

Do you have pointers what causes the additional 20 minutes when you generate the whole data set?

(For my tests I didn't change any code, all I did was limit the input data by supplying command line arguments and extracting only relevant data from JSON in my loader.)

**Comment by jonschlinkert** [comment] 2015-02-27 14:51
yes, @doowb and I have been talking about this. The main reason is the [`.mergeContext()` function](https://github.com/jonschlinkert/template/blob/master/index.js#L2142-L2166) in Template. 

It causes by far the biggest lag since the context is constantly being re-built and the context gets merged for every file. This was the main reason for allowing the function to be overridden in the options. But it's not as easy as it should be to customize (with confidence), so it will be little benefit to most users.

We're implementing a solution that we think will help, and we're looking for other places in the code where we're merging/extending objects that can be avoided. but any feedback on how we might make improvements would be great.

**Comment by agross** [comment] 2015-02-27 15:34
The question is, will `mergeContext` run slower with more items? I mean slower as in O(log n)? [It](https://github.com/jonschlinkert/template/blob/master/index.js#L2163) almost looks like it.

**Comment by jonschlinkert** [comment] 2015-02-27 16:58
we've been trying to figure that out. I really have no clue yet. If the objects are accumulating nested properties, like how the `data` object was merged onto the `product` object you had, then it seems like a possibility. something we need to figure out

**Comment by agross** [comment] 2015-02-27 18:20
Since I don't think I need anything apart from my product template's local data object (i.e. nothing merged in) I'll try to override `mergeContext` with basically a no-op and see if that improves timing.

What's doing this bit exactly?

```js
// Merge in `locals/data` from templates
merge(context, this.cache._context.partials);
```

**Comment by jonschlinkert** [comment] 2015-02-27 22:18
> Since I don't think I need anything apart from my product template's local data object (i.e. nothing merged in)

Yeah, just play around with it and use what works for you. this is a good use case for why we exposed the function. 

> What's doing this bit exactly?

that object  is generated by the `.mergeTypeContext()` method, which - in a nutshell - is used to build up the context for a "type" of template before render, like `partials`, `layouts` etc.

**Comment by agross** [comment] 2015-02-27 22:25
Nope, this doesn't bring any improvement:

```js
assemble.option('mergeContext', function(template, locals) {
  return template.data;
});
```

**Comment by agross** [comment] 2015-02-27 22:26
> that object is generated by the .mergeTypeContext() method, which - in a nutshell - is used to build up the context for a "type" of template before render, like partials, layouts etc.

It's actually `undefined` for me.

**Comment by doowb** [comment] 2015-02-27 22:30
The speed is the same when not doing any merging at all?

**Comment by jonschlinkert** [comment] 2015-02-27 22:36
> It's actually undefined for me.

I'll look into it. In the meantime are you using partials or layouts (at the time of inspecting the object)?

**Comment by agross** [comment] 2015-02-27 23:08
@dwoob with the code above in place there's no improvement. 

@jonschlinkert I use a simple hbs layout. The code is basically the same as in my posted sample. Two things on my list for tomorrow: to try the lodash engine and to create a reproduction with my sample for you guys to inspect.

I guess there's a piece of code iterating all templates lurking. Still haven't found decent profiling tools which is a bit sad. WebStorm's spy unfortunately doesn't work at all. 

Good night!

**Comment by jonschlinkert** [comment] 2015-02-27 23:15
> I guess there's a piece of code iterating all templates lurking.

that seems to be the case. thanks for the feedback, we want to get this fixed.

> to try the lodash engine and to create a reproduction with my sample for you guys to inspect.

that's great, everything helps! I have a hunch what it is too, it might be the default loader. which we can easily rip out.

**Comment by agross** [comment] 2015-02-28 12:24
> I guess there's a piece of code iterating all templates lurking.
>> that seems to be the case. thanks for the feedback, we want to get this fixed.

> to try the lodash engine and to create a reproduction with my sample for you guys to inspect.

The template engine doesn't seem to be the culprit. I tried two hbs variants, "full" with two hbs files (product layout uses another layout), "simple" with a single hbs.

![2015-02-28_13-23-22](https://cloud.githubusercontent.com/assets/16245/6426171/0f5c24c8-bf4d-11e4-8a64-405011326a61.png)

>> I have a hunch what it is too, it might be the default loader. which we can easily rip out.

Hm, but I don't even use that. All the templates I'm working with are loaded through my custom loader.

Any ideas what feature to disable/rip out next?

**Comment by agross** [comment] 2015-02-28 16:07
I've updated my sample to a) include a filter (for tests) and b) have more data. All changes are available [in the `data` branch](https://github.com/agross/assemble-custom-loader/tree/data). You can run with filters like this:

```bash
$ assemble -p C -p D
```

This will load and render only cards from `C*.json` and `D*.json`.

Again I ran some tests with smaller and larger data sets and it shows the same behavior w.r.t. big O notation.
![2015-02-28_17-05-41](https://cloud.githubusercontent.com/assets/16245/6426806/12fd2c20-bf6c-11e4-84dc-bf6b87871b62.png)

**Comment by jonschlinkert** [comment] 2015-03-02 02:55
Thanks for digging into this. I've spent several hours this weekend just looking through the codebase for potential culprits. I'm still looking into it, hopefully we can figure this out

**Comment by doowb** [comment] 2015-03-02 06:55
I did a couple of things to try to find where it might be happening:

 - removing registering helpers in `engine-handlebars`: no improvement
 - removing `asset` middleware (the only default `preRender` middleware): no improvement
 - only using `template.data` in `mergeContext`: no improvement
 - removing binding helpers: no improvement
 - removing `applyLayouts`: total time for all went from 11mins to 9mins

Removing the apply layouts was the only thing that I saw any improvement on. Even though there was an improvement, the average per page render time still went up when compared to running a smaller set.

I'll look some more tomorrow. I read [this article from netflix](http://techblog.netflix.com/2014/11/nodejs-in-flames.html) on performance issues they had with express' router and that's why I removed the `preRender` middleware since our router is modeled after their's, but there wasn't an improvement. I'm going to see if some of the tools mentioned in that article work on OSX too. There might be some other profiling tools that are useful, I'm just not familiar with them.

**Comment by agross** [comment] 2015-03-02 20:25
I think I got it. It's [template's `mergeType`](https://github.com/jonschlinkert/template/blob/master/index.js#L1365). 

I ran some tests with profiling enabled and this is what I got (it's [WebStorm 10 EAP](https://confluence.jetbrains.com/display/WI/WebStorm+EAP)'s Tools | V8 Profiling output window):
![2015-03-02_21-02-18](https://cloud.githubusercontent.com/assets/16245/6449243/b5ece20e-c11f-11e4-984b-ecd4974a799e.png)

I then wrapped the `find` method (called by `findRenderable`) in `console.time("find")` and `console.timeEnd("find")` to see how it behaves with small and large datasets. With small datasets I got around 0 to 1 ms, with my full dataset, we're at 60 to 120 ms *per call*.

Then I dug a bit deeper and found that template calls `mergeType` to basically copy the whole dataset for each template to render. There's a nice [`while` loop](https://github.com/jonschlinkert/template/blob/master/index.js#L1374) wrapping a [`for` loop](https://github.com/jonschlinkert/template/blob/master/index.js#L1376).

Just for kicks, I disabled the whole copy logic and just return the cached internal view:

```diff
diff --git a/index.js b/index.js
index b72a6dd..e9ebed4 100644
--- a/index.js
+++ b/index.js
@@ -1364,6 +1364,9 @@ Template.prototype.getType = function(type) {
 
 Template.prototype.mergeType = function(type, collections) {
   debug.template('merging [type]: %s', type);
+
+  if (collections && collections[0])  return this.views[collections[0]]
+
```

So to compare runtimes (in my Ubuntu VM):
* unmodified code, 35 k products: 44 min
* modified code, 35 k products: 6 min

**Comment by doowb** [comment] 2015-03-02 20:37
Wow... that took my run in the `assemble-custom-loader` repo down to 39s.

The basic usage for that method is to be able to find templates of different types that may have the same name based on the search order (which is defined by the `collections` array). I'm sure @jonschlinkert can provide more information on that, but I think we'll be able to revisit that piece of code to try to find a better way of looking up that information.

Thanks for putting the time in to figure this out.

**Comment by jonschlinkert** [comment] 2015-03-02 20:49
this is great, thanks for digging into it.

> 'm sure @jonschlinkert can provide more information on that

Nope, that about covers it. 

> but I think we'll be able to revisit that piece of code to try to find a better way of looking up that information.

yeah, I have a few ideas already. just knowing what the issue is, is 90% of the battle. When I implemented that code the focus was on "making it all work". Now we're focused on optimizing and simplifying. so this is a huge help

**Comment by agross** [comment] 2015-03-02 20:54
The hard part was really to find semi-working profiling tools. WebStorm 10 EAP + node v0.11 on Ubuntu finally seemed to work. (WebStorm's included profiler was so-so.)

I'm eager to test any improvements to the code in question :-)

**Comment by jonschlinkert** [comment] 2015-03-02 21:07
> I'm eager to test any improvements to the code in question :-)

Off-hand, one simple way of eliminating this function is to not do any type-merging by default.  It's becoming obvious that the need for this varies by project, so we would need to allow users/implementors to define a custom function for this if we go that route.

just thinking out loud...

**Comment by jonschlinkert** [comment] 2015-03-02 21:12
@agross since you've been digging into the codebase pretty heavily, do you have any feedback on things that stood out as particularly awkward or clunky? Or anything good that we should do more of?

**Comment by agross** [comment] 2015-03-02 21:23
>  the need for this varies by project

Why would I want that? Any use case of yours?

> do you have any feedback on things that stood out as particularly awkward or clunky

I'm still a JS noob to be honest and I don't feel like I got the reputation to review your code. I still need to do a lot of research and `console.log` to understand what's going on in general - there are so many small libs and concepts that are somewhat new to me. But reading other people's code already improved my JS, so I think it's worthwhile.

Without having looked further and just off the top of my head, I find it strange that there are 4 `template*` modules used by assemble. But I'm willing to accept that ;-)

Other than that, I have the feeling that there are (too) many options in assemble (just learned about strict errors today) that are nowhere documented. And w.r.t strict errors, would that make #644 fail? Does it default to true? If not, why?

Please consider this a brain dump, these things are nothing that I'm really concerned with in my daily assemble work.

**Comment by jonschlinkert** [comment] 2015-03-02 22:03
> Please consider this a brain dump, these things are nothing that I'm really concerned with in my daily assemble work.

I asked for it, no worries! 

>  Why would I want that? Any use case of yours?

We have to pass templates to engines in a way that the engine will understand. If you don't define any custom template types, you wouldn't really need this. But 1) if you define custom template types that will be used as partials (a contrived example might be `includes`, `snippets` and `partials`), and 2) if the engine has support for partials, then at render time we need to pass all of those templates to the template engine _as actual partials_. Which means we need to merge `snippets`, `includes` and `partials` onto a single `partials` object.  

The concept still applies if the engine does not have support for partials (like Lo-Dash), but instead of passing an object of `partials` we need to merge all templates onto the context. In these cases, it gets even trickier since we need to try to avoid collision between template names, helper names, and variable on the context. 

Ideally, we (or the template engine) would be able to traverse a template dependency tree to determine the templates that are actually (going to be) called, then dynamically build up a merge strategy based on that tree. But for now I can't think of another way around it - it's entirely possible that I'm missing something obvious, so feedback or ideas for a different approach would be great. 

> I find it strange that there are 4 template* modules used by assemble. But I'm willing to accept that ;-)

To clarify, do you mean "strange that they are non-assemble modules" or "strange that they are modules and not in assemble-core"? either of those could make sense

> Other than that, I have the feeling that there are (too) many options in assemble (just learned about strict errors today) that are nowhere documented

Okay, good feedback. Some of the options are more of an admittance that we weren't quite sure what a user would expect. Over time we will eliminate options in favor of sensible defaults - and an API that allows developers to work around those defaults when necessary.

**Comment by jonschlinkert** [comment] 2015-03-02 22:08
just throwing any idea into the hat, but we could consider storing templates by unique id, like nanoc and others, so we can eliminate the merging, and implement a lookup table to make it easier to do lookups, find templates by type, name etc.  Using full filepath is not enough, since the same template might appear in multiple collections.

**Comment by agross** [comment] 2015-03-02 22:34
> To clarify, do you mean "strange that they are non-assemble modules" or "strange that they are modules and not in assemble-core"? either of those could make sense

I was talking about `template`, `template-init`, `template-render` and `template-utils`. I wondered why they are not just one lib.

**Comment by jonschlinkert** [comment] 2015-03-03 01:16
`init` and `render` are just vinyl plugins that will probably be used by [verb](https://github.com/assemble/verb) too (I might have used one or both already, can't remember if I got around to it). `template-utils` can be used by implementors and in plugins. `template` is a completely separate project though. you could use template to build your own static site generator if you wanted.

**Comment by jonschlinkert** [comment] 2015-03-29 22:55
@agross is this okay to close?

**Comment by agross** [comment] 2015-03-29 23:12
@jonschlinkert I'd say no because I don't see how I can prevent the non-linearity. Any suggestions? Probably provide a custom override for `mergeType` (https://github.com/assemble/assemble/issues/650#issuecomment-76809402)?

**Comment by jonschlinkert** [comment] 2015-03-29 23:38
good point

> Probably provide a custom override for mergeType

That was my thinking. In addition to that, I just thought of something that would probably have a bigger impact. a specialized method should be created for each of the built-in types (renderable, partial, and layout). 

There is no getting around that fact that if you have multiple "partial" collections (say, `partials`, `snippets`, and `includes` as a contrived example), you will need to merge them before passing them to the engine. It's similar with layouts. But we might not even need to merge renderable collections, which anecdotally seems like those collections would usually be the largest. not sure if that's the reality.

Also, we can optimize around when the merging is done, and possibly find a way to speed up the actual merge logic.  but I'm not sure how much faster that part can be, given that we need to allow more than two objects to be merged.

any of this sound like a good path?

**Comment by agross** [comment] 2015-03-30 09:15
Sounds good! I'm open to any improvements and will be happy to test them with my project.

**Comment by agross** [comment] 2015-04-08 20:50
Hi guys,

I have a meeting with my (your :) future assemble customer. What should I tell them when we talk about the timing issue and its potential fix?

Thanks!

Alex

**Comment by jonschlinkert** [comment] 2015-04-08 22:47
Oh nice! I didn't know we were splitting the check ;)

**Comment by jonschlinkert** [comment] 2015-04-08 23:01
kidding aside, this is something we want to improve, and I've already started moving some logic out of template to simplify pre-rendering logic just to make it easier to isolate solutions for this. but neither of us really know how much of an impact any of these solutions will ultimately have since, when all is said an done, we're still limited by which data needs to be passed to engines, and how the data needs to be passed.

**Comment by jonschlinkert** [comment] 2015-09-13 03:06
closing since we completely refactored assemble and the responsible underlying libs and this data is now outdated. although it would be great to update this with the latest :)

**Closed by jonschlinkert** 2015-09-13 03:06 UTC
