### ISSUE TITLE
Building a HB template with `$CLASS$` text fails

### ISSUE THREAD

**Issue by evil-shrike** [assemble/assemble#580] opened 2014-10-14 09:17 UTC
I have a template (bad.md.hbs):
```
`$CLASS$`
```
There's a layout specified in Grunt task:
```
---
layout: docpage.hbs
---
{{#markdown}}
  {{> body }} 
{{/markdown}}
```
docpage.hbs is jsut a html markup with `{{> body }} ` somewhere inside. Nothing fancy. 

But when I run `grunt assemble` I'm getting the following error:

Running "assemble:docs" (assemble) task
Assembling _dist/docs/1/bad.html ERROR
Warning: Parse error on line 109:
...}  </body></html>
--------------------^
Expecting 'CONTENT', 'COMMENT', 'OPEN_BLOCK', 'OPEN_INVERSE', 'OPEN_ENDBLOCK', 'OPEN', 'OPEN_UNESCAPED', 'OPEN_PARTIAL', got 'EOF' Use --force to continue.

I can't understand what's wrong with `$CLASS$` markup. Any help is appreciated.

**Comment by knight-dj-et** [comment] 2015-05-13 18:03
I just encountered something like this. In my case, I had a code sample in a .md file, which used a layout your example. 

The problem turned out to be that assemble uses `String.prototype.replace()` to inject the body content into the layout. That's all fine except for that the method uses $ to mean certain special values related to the regex it matches on. $' means output everything after the matching string, so you end up outputting an additional {{\markdown}}, which fails to parse.

**Comment by jonschlinkert** [comment] 2015-05-13 18:07
> uses String.prototype.replace() to inject the body content

this is a bug IMO. as I recall, assemble (0.4.x) will replace multiple body tags, in which case we should be using `.split().join()`, so we don't need to convert to regex that might cause these issues.  we'll look into it. thx for reporting

**Comment by knight-dj-et** [comment] 2015-05-13 18:15
I'm pretty sure assemble (0.4.x) assumes there is only one body and one insertion point for it. Or at least that's what the docs are suggesting and that is how the code is written (i.e. the code doesn't imply it should support multiple insertion points and fails to do that; the code suggests only one is expected). 

In any case the problem is how replace treats $, which is a side-effect of using .replace.

**Comment by jonschlinkert** [comment] 2015-05-13 18:19
closing to move the discussion to grunt-assemble

**Comment by knight-dj-et** [comment] 2015-05-13 18:19
It would be a 1 line change on https://github.com/assemble/assemble/blob/v0.4.42/tasks/assemble.js#L700

change 
```
layout.replace(assemble.engine.bodyRegex, body);
```

to
```
layout.replace(assemble.engine.bodyRegex, body.replace("$", "$$$$"));
```

**Closed by jonschlinkert** 2015-05-13 18:19 UTC
Labels: bug

**Comment by jonschlinkert** [comment] 2015-05-13 18:21
please make comments on the linked issue. thanks
