### ISSUE TITLE
v0.6.0 dest error

### ISSUE THREAD

**Issue by Melindrea** [assemble/assemble#706] opened 2015-05-07 11:36 UTC
I can use the following "plugin" as-is in gulp, but not in assemble. (the purpose of it doesn't matter atm, but I need use it in Assemble, not in gulp).

 ```
'use strict';

var through = require('through2'),
    path = require('path'),
    entries = [];
module.exports = function () {
    return through.obj(function (file, enc, cb) {
        cb();
    },
    function (cb) {
        var contents = '{}',
            gutil = require('gulp-util'),
            file = new gutil.File({
                cwd: process.cwd(),
                base: '/data/',
                path: '/data/files.json',
                contents: new Buffer(contents)
            });
        this.push(file);
        cb();
    });
};
```

Asemble task and gulp task are identical (except replacing assemble with gulp):

```
var bufferPages = require('plugin');
assemble.task('buffer', function () {
    assemble.src('content/pages/**/*.md')
        .pipe(bufferPages())
        .pipe(assemble.dest('data'));
});
```

Error message: 
```
/home/marie/projects/smaty.se/node_modules/gulp-util/lib/PluginError.js:102
    return '    ' + prop + ': ' + self[prop];
                                ^
TypeError: Cannot convert object to primitive value
    at stringifyProperty (/home/marie/projects/smaty.se/node_modules/gulp-util/lib/PluginError.js:102:33)
    at Array.map (native)
    at PluginError._messageDetails (/home/marie/projects/smaty.se/node_modules/gulp-util/lib/PluginError.js:101:27)
    at PluginError._messageWithDetails (/home/marie/projects/smaty.se/node_modules/gulp-util/lib/PluginError.js:80:22)
    at PluginError.toString (/home/marie/projects/smaty.se/node_modules/gulp-util/lib/PluginError.js:124:16)
    at Stream.<anonymous> (/home/marie/projects/smaty.se/node_modules/assemble/node_modules/assemble-utils/node_modules/session-cache/node_modules/continuation-local-storage/context.js:78:13)
    at Stream.emit (events.js:104:17)
    at Stream.emitted [as emit] (/home/marie/projects/smaty.se/node_modules/assemble/node_modules/assemble-utils/node_modules/session-cache/node_modules/continuation-local-storage/node_modules/emitter-listener/listener.js:122:21)
    at DestroyableTransform.handleEnd (/home/marie/projects/smaty.se/node_modules/assemble/node_modules/event-stream/node_modules/duplexer/index.js:81:21)
    at DestroyableTransform.emit (events.js:129:20)
```

**Comment by jonschlinkert** [comment] 2015-05-07 14:13
> the purpose of it doesn't matter atm, but I need use it in Assemble, not in gulp

Well, it might matter. Assemble uses session caching to allow data to be shared across tasks, gulp doesn't. You need to ensure that the same object that's loaded is the one that's being passed to the render method later in the pipeline.

**Comment by Melindrea** [comment] 2015-05-07 14:15
Alright, so it's not possible to in assemble load in a bunch of files, compile data from them and create a new file with that data?

**Comment by stefanwalther** [comment] 2015-05-30 11:31
That's exactly what I am trying, too - using gulp-sitemap.
Getting the following error:

```js
Cannot read property 'dest' of undefined
prop error@context
D:\Projects\Node.js\assemble\node_modules\gulp-util\lib\PluginError.js:114
    return '    ' + prop + ': ' + self[prop];
                                ^
TypeError: Cannot convert object to primitive value

```
(Note: I have added some console.logs to get some info about the "Cannot convert object" error)

@Melindrea, did you succeed?

**Comment by Melindrea** [comment] 2015-05-30 16:24
Not yet, I use gulp-sitemap via gulp, and am looking into a hand-written solution that'll read the yaml frontmatter and use it outside of Assemble. Not ideal (at all), but it'll work.

**Comment by jonschlinkert** [comment] 2015-05-30 16:39
we do this in the built-in plugins. The problem is that you're pushing files into the stream as vinyl files, which are then passed to the `.render` method (as vinyl files, _not as templates_). e.g. gulp won't have an issue with it, since gulp is just passing a vinyl file through. 

The mostly likely causes of the issue you're having are:

- there is no `content` property -  this should be a string (same conventions and properties as Assemble 0.4.x)
- there is no engine registered for `.json` files so the default engine is trying to render them, but doesn't know how (this probably isn't it)

There are other potential causes but those are the two most likely. Try running assemble with:

```js
assemble.enable('minimal config');
```

See if the files render the way you want. Note, however, that this will also turn off most of the defaults, including the default engine). It's pretty easy to register engines though, let me know if this helps.

**Comment by jonschlinkert** [comment] 2015-05-30 16:47
might be worth looking through how some of this is [handled in verb](https://github.com/verbose/verb/tree/master/lib). I'm trying to get everything simplified and using the same core code so we can ensure that plugins work with gulp, verb, assemble etc. it's getting there...

**Comment by jonschlinkert** [comment] 2015-09-13 03:08
closing based on age and since it's not a bug

**Closed by jonschlinkert** 2015-09-13 03:08 UTC
