### ISSUE TITLE
Less generation in v0.6.0 not working properly

### ISSUE THREAD

**Issue by stefanwalther** [assemble/assemble#658] opened 2015-03-10 13:05 UTC
Hi,

I have used one of the examples:

```javascript
assemble.task( 'less', function () {
	assemble.src( './src/less/_root.less' )
		.pipe( require( 'gulp-debug' )() )
		.pipe( less() )
		.pipe( assemble.dest( './public/temp/css' ) );
} );
```

running, *but* the output is the default rendering of my default template, and not the less-css conversion ouput. Less files are correct, tried the same in gulp with the appropriate output:

```javascript
gulp.task( 'less', function () {
	return gulp.src( './src/less/_root.less' )
		//.pipe( require( 'gulp-debug' )() )
		.pipe( less() )
		.pipe( gulp.dest( './public/temp/css/' ) );
} );

gulp.task( 'default', ['less'] );
```

**Comment by doowb** [comment] 2015-03-10 13:08
What's the name of your default template?

**Comment by stefanwalther** [comment] 2015-03-10 13:17
./src/layouts/**.hbs and in this folder I only have "default.hbs"

**Comment by doowb** [comment] 2015-03-10 13:27
Do you have any other file named `_root` that might have been loaded already? I'm trying to find where the bug might be because we're using the same thing and it's working fine. If you have an example repository that reproduces the issue that we can look at, it would help.

**Comment by stefanwalther** [comment] 2015-03-10 13:59
Np, I'll upload a sample repository ... wanted to do that anyhow since I am starting to work with v0.6.0 I think it's good for me (and also for other people) to have a working sample repository somewhere ... ;-)

**Comment by stefanwalther** [comment] 2015-03-10 14:06
Here we go: https://github.com/stefanwalther/assemble-sample/blob/master/assemblefile.js#L35

**Comment by jonschlinkert** [comment] 2015-03-10 20:32
@doowb remember I was having issues getting the gulp-less plugin to work as well. I didn't spend enough time with it to debug but I can revisit

**Comment by stefanwalther** [comment] 2015-03-15 20:35
Hi, any news on this?

**Comment by jonschlinkert** [comment] 2015-03-15 20:37
Sorry, not yet. @doowb I think we just need to add a simple check in the render plugin that pushes the file into the stream if the extension doesn't match a registered engine.

**Comment by onokumus** [comment] 2015-04-25 21:27
@stefanwalther 
Modify this line https://github.com/stefanwalther/assemble-sample/blob/master/assemblefile.js#L39
```javascript
 assemble.src( './src/less/_root.less', {layout: null} )
```

**Comment by jonschlinkert** [comment] 2016-01-15 03:36
closing since this refers to an outdated version of assemble and has been resolved

**Closed by jonschlinkert** 2016-01-15 03:36 UTC
